### ISSUE TITLE
Error while running Fungible Example

### ISSUE THREAD

**Issue by karthiksukumaran** [hyperledger-labs/fabric-token-sdk#195]
Hi All, Thank in advance. 
Getting the below error while running the Fungible example

`
cd $GOPATH/src/github.com/hyperledger-labs/fabric-token-sdk/samples/fabric/fungible

go build -o fungible

./fungible network start --path ./testdata
`

```
panic: No future change is possible.  Bailing out early after 93.379s.
Expected
    <int>: 1
to match exit code:
    <int>: 0

goroutine 1 [running]:
github.com/hyperledger-labs/fabric-smart-client/integration.failMe({0xc000cd2080, 0x16}, {0xc0004b53a0, 0x5, 0x5})
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/integration.go:338 +0x2d
github.com/onsi/gomega/internal.(*AsyncAssertion).match.func1({0x13fd22f, 0x30})
        /root/go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/async_assertion.go:169 +0x31d
github.com/onsi/gomega/internal.(*AsyncAssertion).match(0xc000c7b630, {0x16dcf90, 0xc00076dea8}, 0x1, {0x0, 0x0, 0x0})
        /root/go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/async_assertion.go:179 +0x5e8
github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0xc000c7b630, {0x16dcf90, 0xc00076dea8}, {0x0, 0x0, 0x0})
        /root/go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/async_assertion.go:92 +0x6b
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.InstallChaincode(0xc0001428c0, 0xc0000b49c0, {0xc0001115b0, 0x1, 0xcd003f})
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/fabric/network/deploy.go:79 +0xf3
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.PackageAndInstallChaincode(0x0, 0xc0000b49c0, {0xc0001115b0, 0x1, 0x1})
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/fabric/network/deploy.go:51 +0x2d2
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.(*Network).DeployChaincode(0xc0001428c0, 0xc0000b49c0)
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/fabric/network/network.go:313 +0x26a
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric/network.(*Network).PostRun(0xc0001428c0, 0x0)
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/fabric/network/network.go:227 +0x345
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/fabric.(*Platform).PostRun(0xc00019c298, 0x0)
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/fabric/fabric.go:169 +0x45
github.com/hyperledger-labs/fabric-smart-client/integration/nwo.(*NWO).Start(0xc0000344d0)
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/nwo.go:147 +0x69f
github.com/hyperledger-labs/fabric-smart-client/integration.(*Infrastructure).Start(...)
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/integration.go:185
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd/network.Start({0xc00035ac90, 0x3, 0x3})
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/cmd/network/cmd.go:170 +0x230
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd/network.StartCmd.func1(0xc000233b80, {0xc000117b60, 0x2, 0x2})
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/cmd/network/cmd.go:129 +0x65
github.com/spf13/cobra.(*Command).execute(0xc000233b80, {0xc000117b20, 0x2, 0x2})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000388dc0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/hyperledger-labs/fabric-smart-client/integration/nwo/cmd.(*Main).Execute(0xc00035a600)
        /root/go/pkg/mod/github.com/hyperledger-labs/fabric-smart-client@v0.0.0-20220302104532-f1f2fa782bea/integration/nwo/cmd/main.go:56 +0x256
main.main()
        /home/blockchain/go/gopath/src/github.com/hyperledger-labs/fabric-token-sdk/samples/fabric/fungible/fungible.go:36 +0x105

```

**Comment by adecaro** [comment]
Hi @karthiksukumaran, thanks for reaching out.

Can you attach the rest of the logs you get, please? On which OS are you running this?

It looks like the installation of the token chaincode times out. Let's understand better why :)

**Comment by adecaro** [comment]
@santamit , please, can you try with the latest main branch commit?

**Comment by adecaro** [comment]
@santamit , any update? Can we close this?

**Comment by santamit** [comment]
@adecaro - Yes that worked so please close it. Thanks for your helps.

**Comment by adecaro** [comment]
Thanks
